version: "3.4"

services:
  web:
    image: registry.gitlab.com/trq-fundacion/api-monitoreo:v1-0-0
    command: uvicorn app.main:app --host 0.0.0.0
    env_file: .env
    volumes:
      - .:/app
    ports:
      - ${API_PORT}:8000 
