version: "3.4"

services:
  #databases
  AuthDBA:
    image: postgres:15-bullseye
    command: postgres -c max_connections=1000
    env_file: .env.alpha.smc
    ports:
      - ${DATABASE_PORT_EXPOSE}:${DATABASE_PORT}
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    restart: on-failure
    volumes:
      - AuthDBA_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.alpha.smc
    ports:
      - ${API_PORT}:${FASTAPI_PORT}
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    restart: on-failure
    depends_on:
      - AuthDBA

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - ${DATABASE_UI_PORT_EXPOSE}:${DATABASE_UI_PORT}
    volumes:
      - /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace-api-monitoreo
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    restart: on-failure
    depends_on:
      - AuthDBA

volumes:
  AuthDBA_data: