version: "3.4"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.alpha
    ports:
      - ${API_PORT}:${FASTAPI_PORT}
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    restart: on-failure